# yaml-language-server: $schema=https://json-schema.axonivy.com/14.0/config/variables.json
Variables:
  metaproc:
    Url: http://localhost:8080
    Username: admin
    Password: 1234
    # Token expiration in minutes
    TokenExpiredDuration: 60
