# yaml-language-server: $schema=https://json-schema.axonivy.com/app/13.2.1/rest-clients.json
RestClients:
  metaproc:
    UUID: dd465626-dd32-4679-886d-b85d740a345c
    Url: ${ivy.var.metaproc.Url}
    Icon: res:/webContent/icons/metaproc.png
    Features:
    - ch.ivyteam.ivy.rest.client.mapper.JsonFeature
    - com.axonivy.utils.metaproc.auth.AuthTokenFeature
